### ISSUE TITLE
Not working on Android S

### ISSUE THREAD

**Issue by dprh** [systembugtj/AutoUpdate#4]
Logs:
 java.lang.IllegalArgumentException: com.perform_vr.miragym.remote: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                        Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                        	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
                                                                                        	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
                                                                                        	at android.app.PendingIntent.getActivity(PendingIntent.java:451)
                                                                                        	at android.app.PendingIntent.getActivity(PendingIntent.java:415)
                                                                                        	at com.artwl.update.DownloadService.updateProgress(DownloadService.java:162)
                                                                                        	at com.artwl.update.DownloadService.onHandleIntent(DownloadService.java:114)

**Comment by dprh** [comment]
I corrected it and updated to androidX etc. Can push the update if you give me access.
